### ISSUE TITLE
Apolline crashes upon starting

### ISSUE THREAD

**Issue by rouvoy** [Apolline-Lille/apolline-android#10]
When pairing the phone with the sensor and launching the Apolline app, the latter fails to report any value and crashes after a few seconds (cf. trace below).

Phone:
- Phone model: `MI 6`
- Android version: `7.1.1 NMF26X`
- stack trace :
```
java.lang.IllegalStateException: Cannot access database on the main thread since it may potentially lock the UI for a long period of time.
	at android.arch.persistence.room.RoomDatabase.assertNotMainThread(RoomDatabase.java:164)
	at android.arch.persistence.room.RoomDatabase.beginTransaction(RoomDatabase.java:211)
	at science.apolline.database.SensorDao_Impl.insertOne(SensorDao_Impl.java:190)
	at science.apolline.sensor.common.sensorViewModel.setPersistant(sensorViewModel.kt:71)
	at science.apolline.sensor.common.sensorViewModel.access$setPersistant(sensorViewModel.kt:26)
	at science.apolline.sensor.common.sensorViewModel$BReceiver$1.onReceive(sensorViewModel.kt:41)
	at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:308)
	at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
	at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:118)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:160)
	at android.app.ActivityThread.main(ActivityThread.java:6252)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:895)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:785)
```

**Comment by kaal-dam** [comment]
the allowMainThreadQuerry call was forgotten during the database refactor commit [https://github.com/Apolline-Lille/apolline-android/commit/124cf7bc0d6b21b756f13c6938f6d6b90e56a2ce](url)
